In [50]:
import pandas as pd
data=pd.read_csv('system_analysis.csv',index_col=0)
data.head(10)

,DEV,tps,rd_sec/s,wr_sec/s,avgrq-sz,avgqu-sz,await,svctm,%util
10:30:01,,,,,,,,,
10:40:01,dev253-0,2631.99,330506.47,1791.10,126.25,2.32,0.88,0.07,19.49
10:51:23AM,dev253-0,1749.34,238676.64,813.17,136.90,1.23,0.70,0.09,16.56
11:00:01 M,dev253-0,2088.05,265709.18,1984.63,128.20,1.83,0.88,0.07,15.58
11:10:15 AM,dev253-0,2489.68,346712.12,1561.12,139.89,2.42,0.97,0.08,20.07
11:20:01 AM,dev253-0,1021.72,162904.26,1110.22,160.53,0.76,0.75,0.13,13.59
11:30:02 AM,dev253-0,16.48,332.30,603.84,117.52,0.05,3.01,0.44,0.72
11:40:02 AM,dev253-0,647.95,89754.03,1838.52,141.36,0.59,0.90,0.11,7.12
11:53:10 AM,dev253-0,1553.44,236367.99,1273.98,152.98,1.29,0.83,0.11,16.74
12:04:06 PM,dev253-0,581.85,89478.77,1685.24,156.68,0.41,0.70,0.14,8.29

In [53]:
feature_column=['tps','rd_sec/s','wr_sec/s','avgrq-sz','avgqu-sz','avgqu-sz','await','%util']
data[feature_column]

,tps,rd_sec/s,wr_sec/s,avgrq-sz,avgqu-sz,avgqu-sz,await,%util
10:30:01,,,,,,,,
10:40:01,2631.99,330506.47,1791.10,126.25,2.32,2.32,0.88,19.49
10:51:23AM,1749.34,238676.64,813.17,136.90,1.23,1.23,0.70,16.56
11:00:01 M,2088.05,265709.18,1984.63,128.20,1.83,1.83,0.88,15.58
11:10:15 AM,2489.68,346712.12,1561.12,139.89,2.42,2.42,0.97,20.07
11:20:01 AM,1021.72,162904.26,1110.22,160.53,0.76,0.76,0.75,13.59
11:30:02 AM,16.48,332.30,603.84,117.52,0.05,0.05,3.01,0.72
11:40:02 AM,647.95,89754.03,1838.52,141.36,0.59,0.59,0.90,7.12
11:53:10 AM,1553.44,236367.99,1273.98,152.98,1.29,1.29,0.83,16.74
12:04:06 PM,581.85,89478.77,1685.24,156.68,0.41,0.41,0.70,8.29

In [101]:
length=data.shape[0]
tps_value=data[feature_column]['tps'].values
for i in range(length):
    if  tps_value[i] > 2000.00:
        data['Behaviour']='Abnormal'
        print "here",i
    else:
        data['Behaviour']='yes'
        print "there",i

here 0
there 1
here 2
here 3
there 4
there 5
there 6
there 7
there 8

In [97]:
x=data['tps'].values
x[0]>2000.00

True

In [102]:
data.head(10)

,DEV,tps,rd_sec/s,wr_sec/s,avgrq-sz,avgqu-sz,await,svctm,%util,Behaviour
10:30:01,,,,,,,,,,
10:40:01,dev253-0,2631.99,330506.47,1791.10,126.25,2.32,0.88,0.07,19.49,yes
10:51:23AM,dev253-0,1749.34,238676.64,813.17,136.90,1.23,0.70,0.09,16.56,yes
11:00:01 M,dev253-0,2088.05,265709.18,1984.63,128.20,1.83,0.88,0.07,15.58,yes
11:10:15 AM,dev253-0,2489.68,346712.12,1561.12,139.89,2.42,0.97,0.08,20.07,yes
11:20:01 AM,dev253-0,1021.72,162904.26,1110.22,160.53,0.76,0.75,0.13,13.59,yes
11:30:02 AM,dev253-0,16.48,332.30,603.84,117.52,0.05,3.01,0.44,0.72,yes
11:40:02 AM,dev253-0,647.95,89754.03,1838.52,141.36,0.59,0.90,0.11,7.12,yes
11:53:10 AM,dev253-0,1553.44,236367.99,1273.98,152.98,1.29,0.83,0.11,16.74,yes
12:04:06 PM,dev253-0,581.85,89478.77,1685.24,156.68,0.41,0.70,0.14,8.29,yes